site_name: "Deranged Senators Documentation"


theme:
    name: material
    favicon: images/favicon.ico
    features:
        - navigation.tabs
        - toc.integrate
        - navigation.instant
    
    palette:
        - scheme: default
          primary: blue
          accent: light blue
extra:
    social: # Footer SM Links
        - icon: fontawesome/brands/github
          link: https://github.com/DerangedSenators
          name: DerangedSenators on Github
markdown_extensions:
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg # Resource for icons: https://squidfunk.github.io/mkdocs-material/getting-started/#icons
plugins:
  - search
  - awesome-pages:
        filename: pages.yml
copyright: Copyright &copy; 2020 Deranged Senators
