name: Publish Documentation
on:
  push:
  pull_request:
      branches:
      - gh-pages
  repository_dispatch:
    types: [deploy]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure git
        env:
          TOKEN: ${{ secrets.BUILD_BOT_KEY }}
        run: git config --global url."https://${TOKEN}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
      - name: Build Documentation
        shell: bash
        run: |
          ls
          sudo chmod +x getdocs.sh 
          sudo chmod +x doxygen/doxybook2
          sudo ./getdocs.sh
      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          ACCESS_TOKEN: ${{ secrets.BUILD_BOT_KEY }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: public # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
